name: Sync Receiver

on:
  push:
    paths:
      - 'main.js'
    branches:
      - main

jobs:
  notify-receiver:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger receiver repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/luanapaes/receiver/dispatches \
            -d '{
              "event_type": "sync_main_js"
            }'